spring:
  datasource:
    url: jdbc:sqlserver://sandalikaserver.database.windows.net:1433;database=sandalikadb;user=sandalikaliyanage@sandalikaserver;password=Sandalika24;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: sandalikaliyanage
    password: Sandalika24
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191
